# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI sync finance tiktok k

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      # TABLE_FINANCE_NAME:
      #   description: "Tên bảng finance"
      #   required: true
      #   type: string

      FROM_FINANCE:
        description: "Từ ngày (YYYY/MM/DD)"
        required: true
        type: string

      TO_FINANCE:
        description: "Đến ngày (YYYY/MM/DD)"
        required: true
        type: string

jobs:
  sync-finance-job:
    runs-on: ubuntu-latest
    environment: sync-data-tiktok-k

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run sync-finance-k.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
          AES_256_CBC_APP_SECRET_KEY: ${{ secrets.AES_256_CBC_APP_SECRET_KEY }}
          TIKTOK_PARTNER_APP_KEY_7561567100864644872: ${{ secrets.TIKTOK_PARTNER_APP_KEY_7561567100864644872 }}
          TIKTOK_PARTNER_APP_SECRET_7561567100864644872: ${{ secrets.TIKTOK_PARTNER_APP_SECRET_7561567100864644872 }}
          LARK_TIKTOK_K_ORDER_ITEMS_APP_ID: ${{ secrets.LARK_TIKTOK_K_ORDER_ITEMS_APP_ID }}
          LARK_TIKTOK_K_ORDER_ITEMS_APP_SECRET: ${{ secrets.LARK_TIKTOK_K_ORDER_ITEMS_APP_SECRET }}
          BASE_ID_TMDT: ${{ secrets.BASE_ID_TMDT }}
          TABLE_FINANCE_NAME: ${{ vars.TABLE_FINANCE_NAME }}
          FROM_FINANCE: ${{ inputs.FROM_FINANCE || vars.FROM_FINANCE }}
          TO_FINANCE: ${{ inputs.TO_FINANCE || vars.TO_FINANCE }}

        run: node sync-finance-k.js
