# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nodejs sync finance tiktok k

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      TABLE_NAME:
        description: "Tên bảng finance"
        required: false
        type: string

      FROM:
        description: "Từ ngày (YYYY/MM/DD)"
        required: false
        type: string

      TO:
        description: "Đến ngày (YYYY/MM/DD)"
        required: false
        type: string

jobs:
  sync-finance-job:
    runs-on: ubuntu-latest
    environment: sync-finance

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run sync-finance-k.js
        env:
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
          AES_256_CBC_APP_SECRET_KEY: ${{ secrets.AES_256_CBC_APP_SECRET_KEY }}
          TIKTOK_PARTNER_APP_KEY_7561567100864644872: ${{ secrets.TIKTOK_PARTNER_APP_KEY_7561567100864644872 }}
          TIKTOK_PARTNER_APP_SECRET_7561567100864644872: ${{ secrets.TIKTOK_PARTNER_APP_SECRET_7561567100864644872 }}
          LARK_TIKTOK_K_ORDER_ITEMS_APP_ID: ${{ secrets.LARK_TIKTOK_K_ORDER_ITEMS_APP_ID }}
          LARK_TIKTOK_K_ORDER_ITEMS_APP_SECRET: ${{ secrets.LARK_TIKTOK_K_ORDER_ITEMS_APP_SECRET }}
          BASE_ID_TMDT: ${{ vars.BASE_ID_TMDT }}
          TABLE_NAME: ${{ inputs.TABLE_NAME || vars.TABLE_NAME }}
          FROM: ${{ inputs.FROM || vars.FROM }}
          TO: ${{ inputs.TO || vars.TO }}

        run: node sync-finance-k.js
